# Generated by Django 3.2 on 2023-02-06 07:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('3d0eea26-8180-456d-9b22-91012a1ccdae'), editable=False, verbose_name='Код подтверждения'),
        ),
    ]
