# Generated by Django 3.2 on 2023-02-06 08:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('fa2d1908-bd8f-41bb-a211-a6a8f5d1c493'), editable=False, verbose_name='Код подтверждения'),
        ),
    ]
