# Generated by Django 3.2 on 2023-02-06 09:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('ec4b50d2-97c2-4338-b5d9-5b6dbbb5a885'), editable=False, verbose_name='Код подтверждения'),
        ),
    ]
