# Generated by Django 3.2 on 2023-02-06 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230206_1036'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genretotitle',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='genretotitle',
            name='title',
        ),
        migrations.RemoveField(
            model_name='title',
            name='category',
        ),
        migrations.RemoveField(
            model_name='title',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='GenreToTitle',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
