# Generated by Django 3.2 on 2023-01-31 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230131_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='group',
        ),
        migrations.AddField(
            model_name='title',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.category'),
            preserve_default=False,
        ),
    ]
