# Generated by Django 3.2 on 2023-02-03 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_title'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_title_author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
