# Generated by Django 3.2 on 2023-02-03 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230203_1911'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Titles',
        ),
    ]
